name: Auto Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v5

      - name: Build and upload binaries
        uses: wangyoucao577/go-release-action@v1.55
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_path: ./cmd/lacrima
          binary_name: lacrima
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          release_tag: ${{ github.ref_name }}
          overwrite: true
          compress_assets: FALSE
          md5sum: FALSE